# Generated by Django 3.2.20 on 2023-08-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_yourimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourImageModel',
        ),
    ]
